# Generated by Django 4.1.7 on 2023-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pjmanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjcode', models.CharField(max_length=10)),
                ('optcode', models.CharField(max_length=10)),
                ('pjname', models.TextField()),
                ('end_day', models.DateTimeField(blank=True, null=True)),
                ('come_day', models.DateTimeField(blank=True, null=True)),
                ('dead_day', models.DateTimeField(blank=True, null=True)),
                ('first_rate', models.FloatField()),
                ('finance_rate', models.FloatField()),
                ('end_rate', models.FloatField()),
                ('end_profit', models.IntegerField()),
                ('diff_ing', models.FloatField()),
                ('fund', models.IntegerField()),
                ('pf_remain', models.IntegerField()),
                ('cash_year', models.IntegerField()),
                ('cash_all', models.IntegerField()),
            ],
        ),
    ]
